# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c46c476d8088194fdf83dd61785f7b0a0680fd920f6b541cea69efabe58777cff092eb1073d60c8598cc21a2abc23506ff86b3e84c0c8fccbc9d8cc53072ed2

test:
  secret_key_base: 99938b2d0545f697b413711bf14933fb4c9e2d9ed49d34fd1088ac9a2725d33c4f15f929821cae66097ed51ba609f0b32f2e4e76f8890dffd22779acfe5b38f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
